services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: trippick
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tripick-network

  redis:
    image: ${REDIS_IMAGE}
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"  # Redis Insight용 (stack만 해당)
    volumes:
      - redis-data:/data
    networks:
      - tripick-network

  ollama:
    build:
      context: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    tty: true
    networks:
      - tripick-network

  backend:
    build:
      context: ./backend
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECURE: ${COOKIE_SECURE}
      COOKIE_SAMESITE: ${COOKIE_SAMESITE}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_CHAT_MODEL: ${OLLAMA_CHAT_MODEL}
      OLLAMA_EMBED_MODEL: ${OLLAMA_EMBED_MODEL}
    networks:
      - tripick-network


volumes:
  mysql-data:
  redis-data:
  ollama-models:

networks:
  tripick-network:
    name: tripick-network