spring:
  application:
    name: enjoytrip_08

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trippick
    username: ssafy
    password: ssafy
    hikari:
      idle-timeout: 300000
      minimum-idle: 3
      maximum-pool-size: 5
      connection-timeout: 600000

  data:
    redis:
      host: localhost
      port: 6379

  ai:
    openai:
      api-key: 
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-completion-tokens: 10000

    vectorstore:
      redis:
        initialize-schema: true
        index: ssafy-index
        prefix: "ssafy:"

mybatis:
  mapper-locations: classpath:/domain/**/mapper/*.xml
  type-aliases-package: com.ssafy.live.**.dto

jwt:
  secret: S!f9@F3#k2zPq8LuBxM9rH7eT6aWvYu1

logging:
  level:
    com.ssafy: trace
    org.springframework.ai.chat.client.advisor: debug
