server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: enjoytrip_08

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/trippick
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  ai:
    model:
      embedding: ollama  # 임베딩 모델 유형 지정
    ollama:
      base-url: http://ollama:11434
      chat:
        options:
          model: mistral
          temperature: 0.7
          max-completion-tokens: 100
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      redis:
        initialize-schema: true
        index: ssafy-index
        prefix: "ssafy:"

mybatis:
  mapper-locations: classpath:/domain/**/mapper/*.xml
  type-aliases-package: com.ssafy.live.**.dto

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.ssafy: trace
    org.springframework.ai.chat.client.advisor: debug

custom:
  cookie:
    secure: ${COOKIE_SECURE:false}
    samesite: ${COOKIE_SAMESITE:Lax}
