name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Pull latest code and create .env.prod on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} <<EOF
            cd ~/team8-Tripick-BE
            git pull origin main

            echo "DB_USERNAME=${{ secrets.ENV_DB_USERNAME }}" > .env.prod
            echo "DB_PASSWORD=${{ secrets.ENV_DB_PASSWORD }}" >> .env.prod
            echo "REDIS_HOST=${{ secrets.ENV_REDIS_HOST }}" >> .env.prod
            echo "REDIS_IMAGE=${{ secrets.REDIS_IMAGE }}" >> .env.prod
            echo "JWT_SECRET=${{ secrets.ENV_JWT_SECRET }}" >> .env.prod
            echo "COOKIE_SECURE=${{ secrets.ENV_COOKIE_SECURE }}" >> .env.prod
            echo "COOKIE_SAMESITE=${{ secrets.ENV_COOKIE_SAMESITE }}" >> .env.prod
          EOF

      - name: Build and Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} <<EOF
            cd ~/team8-Tripick-BE
            docker-compose --env-file .env.prod down
            docker-compose --env-file .env.prod pull
            docker-compose --env-file .env.prod up -d --build
          EOF
