name: PR Notification to Mattermost

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send PR notification to Mattermost
        env:
          MM_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.actor }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "$(jq -n \
            --arg text ":bell: Pull Request 생성됨!\n> 제목: \"$PR_TITLE\"\n> 작성자: \"$PR_AUTHOR\"\n> 링크: $PR_URL" \
            '{text: $text}')" \
          "$MM_WEBHOOK_URL"
