name: PR Notification to Mattermost

on:
  pull_request:
    types: [opened, reopened]  # PR 생성 또는 다시 열릴 때 작동

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send PR to Mattermost
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          -d '{
                "text": ":bell: Pull Request 생성됨!\n> 제목: '${{ github.event.pull_request.title }}'\n> 작성자: '${{ github.actor }}'\n> 링크: '${{ github.event.pull_request.html_url }}'"
              }' \
          ${{ secrets.MATTERMOST_WEBHOOK_URL }}
